### PR TITLE
Fix Automatic full screen mode for card detail in feed when filters visible (#5101)

### LINKED ISSUE #5101: Automatic full screen mode for card  detail in feed does not work well when fitlers visible
We should not end up with the following screenshot with the detail card too small . In this particular case card should be in full screen 

Capture

### PR DESCRIPTION
**Pull request by quinarygio**
Fix #5101

- In release note :
  -  In chapter :  Bugs 
  -  Text : #5101 : Fix Automatic full screen mode for card detail in feed when filters visible

### CODE REVIEW

File: ui/main/src/app/modules/card/components/card-body/card-body.component.ts [hunk 1]
```diff
@@ -343,7 +343,13 @@ export class CardBodyComponent implements OnChanges, OnInit, OnDestroy {
     }
 
     public isSmallscreen() {
-        return window.innerWidth < 1000;
+        const domElement = document.getElementsByTagName('of-card-body');
+        const width =  domElement.item(0).getBoundingClientRect().width;
```
Comment (freddidierRTE) [inline ui/main/src/app/modules/card/components/card-body/card-body.component.ts:347]: i suggest to name it cardWidth instead of width

File: ui/main/src/app/modules/card/components/card-body/card-body.component.ts [hunk 2]
```diff
@@ -343,7 +343,13 @@ export class CardBodyComponent implements OnChanges, OnInit, OnDestroy {
     }
 
     public isSmallscreen() {
```
Comment (freddidierRTE) [inline ui/main/src/app/modules/card/components/card-body/card-body.component.ts:345]: I suggest to name it isThereEnoughSpaceToShowCard
