### PR TITLE
Fix mail sending for cards sent to parent entity (#4962)

### LINKED ISSUE #4962: When using parent card , mail is not send
To reproduce : 
- configure mail for operator1_fr on state message
- disconnect from operator_1
- connect with operator2_fr , send a message to "French Control Center" 
- wait more than one minute , no mail received 

if you send  a message to Control Center FR North , the mail is received

### PR DESCRIPTION
**Pull request by quinarygio**
Fix #4962 

Nothing in release notes

### CODE REVIEW

File: services/users/src/main/java/org/opfab/users/services/CurrentUserWithPerimetersService.java [hunk 1]
```diff
@@ -30,6 +30,20 @@ public CurrentUserWithPerimetersService(UsersService usersService, UserSettingsS
...
+
+        if (userResp.isPresent()) {
+            User user = userResp.get();
+            currentUserWithPerimetersData.setUserData(user);
+            handleUserSettings(user, currentUserWithPerimetersData);
+            handleGroups(user, currentUserWithPerimetersData);
+            handleEntities(user);
+        }
+        return currentUserWithPerimetersData;
+    }
```
Comment (freddidierRTE) [inline services/users/src/main/java/org/opfab/users/services/CurrentUserWithPerimetersService.java:45]: to avoid duplicated code  , get the user object and if it exists call fetchCurrentUserWithPerimeters(user) 
Add a unit test

**Review by freddidierRTE — CHANGES_REQUESTED** [review]
