### PR TITLE
#1387 Card publication service does not start if rabbit goes up too late 

### LINKED ISSUE #1387: Card publication service does not start if rabbit goes up too late
if card publication is started before rabbit it does not wait for rabbit , it throw an exception 

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-07-05 16:34:38.695 ERROR 490372 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initUpdateUserListener' defined in org.opfab.springtools.configuration.oauth.UpdateUserListenerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.opfab.springtools.configuration.oauth.UpdateUserListener]: Factory method 'initUpdateUserListener' threw exception; nested exception is org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connexion refusée (Connection refused)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.8.jar!/:5.3.8]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.8.jar!/:5.3.8]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.opfab.cards.publication.CardPublicationApplication.main(CardPublicationApplication.java:34) ~[classes!/:SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]

```

The idea would be to wait and try a few time before decided to stop

### PR DESCRIPTION
**Pull request by quinarygio**
Fix #1387

Release notes:

In Bugs section:

#1387 : Card publication service does not start if rabbit goes up too late 

Signed-off-by: Giovanni Ferrari <giovanni.ferrari@soft.it>

### CODE REVIEW

File: services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscription.java [hunk 1]
```diff
@@ -204,13 +207,30 @@ private void registerUserListener(MessageListenerContainer mlc) {
...
+            } catch (AmqpException ex) {
+                if (retry == retries) {
+                    throw ex;
+                }
+                try {
+                    Thread.sleep(retryInterval);
+                } catch (InterruptedException e) {
+                    Thread.currentThread().interrupt();
+                }
+                retry++;
```
Comment (freddidierRTE) [inline services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscription.java:231]: Add a log.info each time we do not succeed with the name of the queue and the retry number

File: services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscriptionService.java [hunk 2]
```diff
@@ -51,6 +51,12 @@
     @Autowired
     protected UserServiceCache userServiceCache;
 
+    @Value("${operatorfabric.amqp.connectionRetries:5}")
+    private int retries;
+
+    @Value("${operatorfabric.amqp.connectionRetryInterval:10000}")
+    private long retryInterval;
```
Comment (freddidierRTE) [inline services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscriptionService.java:58]: Set default value to 10 and 5000

File: tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/UpdateUserListener.java [hunk 3]
```diff
@@ -47,12 +48,29 @@ public UpdateUserListener( AmqpAdmin amqpAdmin, FanoutExchange userExchange, Con
...
+                    throw ex;
+                }
+                try {
+                    Thread.sleep(retryInterval);
+                } catch (InterruptedException e) {
+                    Thread.currentThread().interrupt();
+                }
+                retry++;
+            }
+        }
```
Comment (freddidierRTE) [inline tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/UpdateUserListener.java:73]: To avoid duplication , add this method in a util class in tools/generic/utilities/src/main/java/org/opfab/utilities/amqp.java

**Review by freddidierRTE — CHANGES_REQUESTED** [review]

File: tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/UpdateUserListener.java (hunk 3 above)
Comment (quinarygio) [reply tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/UpdateUserListener.java]: Done

File: services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscriptionService.java (hunk 2 above)
Comment (quinarygio) [reply services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscriptionService.java]: Done

File: services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscription.java (hunk 1 above)
Comment (quinarygio) [reply services/core/cards-consultation/src/main/java/org/opfab/cards/consultation/services/CardSubscription.java]: Done
