### PR TITLE
Fixed date range and translations for date picker in archives and logging (#7800)

### LINKED ISSUE #7800: Archives/Logging : Date range picker does not work for "last month" and "current month"
Cards published on the 31st of the month are excluded.

### LINKED ISSUE #7801: Archives/Logging : missing accents for date range picker
"PERIODE DE PUBLICATION" and "PERIODE D'ACTIVITE"

### PR DESCRIPTION
**Pull request by ClementBouvierN**
Nothing in release notes

### CODE REVIEW

File: ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts [hunk 1]
```diff
@@ -166,7 +165,7 @@ export class ArchivesLoggingFiltersComponent implements OnInit, OnChanges, OnDes
             [last7DaysKey]: [sub(new Date(), {days: 7}).setHours(0, 0, 0, 0), new Date().setHours(24, 0, 0, 0)],
             [last30DaysKey]: [sub(new Date(), {days: 30}).setHours(0, 0, 0, 0), new Date().setHours(24, 0, 0, 0)],
             [thisMonthKey]: [startCurrentMonth, endCurrentMonth],
-            [lastMonthKey]: [startPreviousMonth, endPreviousMonth]
+            [lastMonthKey]: [startPreviousMonth, startCurrentMonth]
```
Comment (vlo-rte) [inline ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts]: Variables xxxKey are not named correctly. These are not keys, 'datePicker.today' for example is a key but then you call getTranslation(). So I would rename them.

**Review by vlo-rte — CHANGES_REQUESTED** [review]

**Review by vlo-rte — APPROVED** [review]
