### PR TITLE
Solve issue :  Exception in console when editing cards (#7526)

### LINKED ISSUE #7526: Exception in console when editing cards
Sometimes when editing a card we have the following exception : 

image

It does not seems to have any impact as the recipients for information are still present

### PR DESCRIPTION
**Pull request by freddidierRTE**
- In release notes :
  -  In chapter :  Bugs
  -  Text : `#7526 Exception in console when editing cards`

### CODE REVIEW

File: ui/main/src/app/modules/share/multi-select/multi-select.component.ts [hunk 1]
```diff
@@ -31,7 +31,10 @@ export class MultiSelectComponent implements AfterViewInit, OnDestroy, OnChanges
     @Output() selectionChange: EventEmitter<string[]> = new EventEmitter<string[]>();
 
     private oldOptions: Array<MultiSelectOption>;
-    private oldSelectedOptions: any;
+    // It is important to initialize it with an empty array an not undefined to avoid
+    // to trigger the change event when no option is selected on the first load
+    // See Issue #7526
+    private oldSelectedOptions: any = new Array<string>();
```
Comment (ClementBouvierN) [inline ui/main/src/app/modules/share/multi-select/multi-select.component.ts]: There is a little typo in the comment, I suggest:
```
    // It is important to initialize it with an empty array and not undefined to avoid
    // triggering the change event when no option is selected on the first load
    // See Issue #7526
```
And I don't think it's necessary to keep the ": any" on the declaration of oldSelectedOptions

**Review by ClementBouvierN — APPROVED** [review]
