### PR TITLE
Fix bug when getting not existing card with slow network (#2993)

### LINKED ISSUE #2993: Not existing card with slow network
Chrome with network set to "Slow 3G" 
Try to access a none existing card via url , for example http://localhost:2002/#/feed/cards/defaultProcess.f6e99672-9f4c-c368-5dde-aff70975f52545
The spinner is showing for ever 

This does not happen with normal network

### PR DESCRIPTION
**Pull request by quinarygio**
Fix #2993

Signed-off-by: Giovanni Ferrari <giovanni.ferrari@soft.it>

- In release note :
  -  In chapter : Bugs
  -  Text : #2993 : Fix bug when getting not existing card with slow network

### CODE REVIEW

File: ui/main/src/app/modules/cards/components/card-details/card-details.component.ts [hunk 1]
```diff
@@ -111,11 +112,14 @@ export class CardDetailsComponent implements OnInit, OnDestroy {
...
     // we show a spinner on screen if card loading takes more than 1 second
     checkForCardLoadingInProgressForMoreThanOneSecond() {
+        console.log("checkForCardLoadingInProgressForMoreThanOneSecond");
         this.store.select(feedSelectors.selectLightCardSelection)
             .pipe(takeUntil(this.unsubscribe$))
             .subscribe((cardId) => {   // a new card has been selected and will be downloaded
                 this.currentSelectedCardId = cardId;
+                console.log("checkForCardLoadingInProgressForMoreThanOneSecond cardId=" + cardId);
                 setTimeout(() => {
+                    console.log("checkForCardLoadingInProgressForMoreThanOneSecond cardNotFound = " +this.cardNotFound);
```
Comment (freddidierRTE) [inline ui/main/src/app/modules/cards/components/card-details/card-details.component.ts:122]: Remove console.log
