### PR TITLE
Fix geolocalization link when card detail is open (#6865)

### LINKED ISSUE #6865: "Geolocalization" link not working when card detail is open
With map view enabled,if a card detail is open, clicking on geolocalization icon in the feed does nothing

image

### PR DESCRIPTION
**Pull request by quinarygio**
Fix #6865

- In release notes :
  -  In chapter : Bugs
  -  Text : #6865 : fix geolocalization link when card detail is open

### CODE REVIEW

File: ui/main/src/app/modules/feed/components/map/map.component.ts [hunk 1]
```diff
@@ -26,15 +26,20 @@ import {OpfabMap} from 'app/modules/share/map/opfab-map';
...
         private translateService: TranslateService,
         private superChangeDetector: ChangeDetectorRef,
-        private router: Router
+        private router: Router,
+        private route: ActivatedRoute
     ) {
         super(translateService, superChangeDetector);
         this.targetElementId = 'ol-map';
         this.filteredLightCardStore = OpfabStore.getFilteredLightCardStore();
+        this.route.queryParams.subscribe((params) => {
```
Comment (freddidierRTE) [inline ui/main/src/app/modules/feed/components/map/map.component.ts]: Maybe add a takeUntil(this.unsubscribe$)

Not sure if it is necessary here , i prefer to be careful

**Review by freddidierRTE — CHANGES_REQUESTED** [review]

**Review by freddidierRTE — APPROVED** [review]
