### PR TITLE
Admin perimeters : fix filter on state rights column (#6379)

### LINKED ISSUE #6379: The ag-grid filter on perimeters column does not work
image

### PR DESCRIPTION
**Pull request by quinarygio**
Fix #6379 

- In release note :
  -  In chapter :  Bugs 
  -  Text : #6379 : Admin perimeters : fix filter on state rights column

### CODE REVIEW

File: ui/main/src/app/modules/admin/components/table/perimeters-table.component.ts [hunk 1]
```diff
@@ -49,16 +49,44 @@ export class PerimetersTableComponent extends AdminTableDirective implements OnI
...
-                            text += currentProcessDef.states.get(stateRight.state).name + ' ';
+                            text += currentProcessDef.states.get(stateRight.state).name.toLocaleLowerCase() + ' ';
                     });
-                    return text;
+
+                    let response = false;
+
+                    switch (params.filterOption) {
+                        case 'equals':
+                            response = text.toLocaleLowerCase() === params.filterText;
```
Comment (vlo-rte) [inline ui/main/src/app/modules/admin/components/table/perimeters-table.component.ts]: When I test with "equals" "message" I have no result. It should return at least the perimeter with id=externalRecipent no ?

File: ui/main/src/app/modules/admin/components/table/perimeters-table.component.ts [hunk 2]
```diff
@@ -49,16 +49,44 @@ export class PerimetersTableComponent extends AdminTableDirective implements OnI
...
+                            response = text.toLocaleLowerCase().indexOf(params.filterText) >= 0;
+                            break;
+                        case 'notContains':
+                            response = text.toLocaleLowerCase().indexOf(params.filterText) < 0;
+                            break;
+                        case 'startsWith':
+                            response = text.toLocaleLowerCase().startsWith(params.filterText);
+                            break;
+                        case 'endsWith':
+                            response = text.toLocaleLowerCase().endsWith(params.filterText);
```
Comment (vlo-rte) [inline ui/main/src/app/modules/admin/components/table/perimeters-table.component.ts]: When I test with "ends with" "message" I have no result. It should return at least the perimeter with id=externalRecipent no ?

**Review by vlo-rte — CHANGES_REQUESTED** [review]

**Review by vlo-rte — APPROVED** [review]
