### PR TITLE
Error messages and status are mixed up in ExternalAppClientImpl (#1547)

### LINKED ISSUE #1547: Error messages and status are mixed up in ExternalAppClientImpl
The error handling in ExternalAppClientImpl is confusing and sometimes inaccurate.

- Messages refer to "businessconfig party" instead of "third party app" or "external app", which can make one think that the problem is with the businessconfig service.
- Some constant strings are not used.
- The value of ERR_CONNECTION_REFUSED doesn't seem coherent.
- The status codes and messages in `callExternalHttpApplication` don't seem appropriate. For example:         

> } catch (IllegalArgumentException ex) {
>             throw new ApiErrorException(ApiError.builder()
>                     .status(HttpStatus.BAD_GATEWAY)
>                     .message(EMPTY_URL_MESSAGE)
>                     .build());
> 

An IllegalArgumentException doesn't necessarily mean that the provided url is empty, and if the provided url is indeed empty the status code shouldn't be bad gateway I think.

I would like to discuss it first to agree on what the correct status code would be for the different error cases.

### PR DESCRIPTION
**Pull request by quinarygio**
Fix  #1547

Release notes

In Bugs section:
#1547 : Error messages and status are mixed up in ExternalAppClientImpl 

Signed-off-by: Giovanni Ferrari <giovanni.ferrari@soft.it>

### CODE REVIEW

File: services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/clients/impl/ExternalAppClientImpl.java [hunk 1]
```diff
@@ -22,11 +31,12 @@
 @Slf4j
 public class ExternalAppClientImpl implements ExternalAppClient {
 
-    public static final String REMOTE_404_MESSAGE = "Specified external application was not handle by businessconfig party endpoint (not found)";
-    public static final String UNEXPECTED_REMOTE_MESSAGE = "Unexpected behaviour of businessconfig party handler endpoint";
-    public static final String EMPTY_URL_MESSAGE = "Url Specified for external application is empty";
+    public static final String REMOTE_404_MESSAGE = "Specified external application was not handled by third party endpoint (not found)";
+    public static final String UNEXPECTED_REMOTE_MESSAGE = "Unexpected behaviour of third party handler endpoint";
```
Comment (freddidierRTE) [inline services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/clients/impl/ExternalAppClientImpl.java:35]: Unexpected behavior of external application endpoint

File: services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/clients/impl/ExternalAppClientImpl.java [hunk 2]
```diff
@@ -22,11 +31,12 @@
 @Slf4j
 public class ExternalAppClientImpl implements ExternalAppClient {
 
-    public static final String REMOTE_404_MESSAGE = "Specified external application was not handle by businessconfig party endpoint (not found)";
-    public static final String UNEXPECTED_REMOTE_MESSAGE = "Unexpected behaviour of businessconfig party handler endpoint";
-    public static final String EMPTY_URL_MESSAGE = "Url Specified for external application is empty";
+    public static final String REMOTE_404_MESSAGE = "Specified external application was not handled by third party endpoint (not found)";
```
Comment (freddidierRTE) [inline services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/clients/impl/ExternalAppClientImpl.java:34]: External application endpoint not found (HTTP 404)

File: services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/clients/impl/ExternalAppClientImpl.java [hunk 3]
```diff
@@ -22,11 +31,12 @@
...
+    public static final String UNEXPECTED_REMOTE_MESSAGE = "Unexpected behaviour of third party handler endpoint";
+    public static final String INVALID_URL_MESSAGE = "Url specified for external application is invalid";
+    public static final String URL_NOT_FOUND_MESSAGE = "Url for external application not configured";
     public static final String NO_EXTERNALRECIPIENTS_MESSAGE = "No external recipients found in the card";
-    public static final String ERR_CONNECTION_REFUSED = "No external recipients found in the card";
+    public static final String ERR_CONNECTION_REFUSED = "I/O exception accessing third party handler endpoint";
```
Comment (freddidierRTE) [inline services/core/cards-publication/src/main/java/org/opfab/cards/publication/services/clients/impl/ExternalAppClientImpl.java:39]: I/O exception accessing external application endpoint

**Review by freddidierRTE — CHANGES_REQUESTED** [review]
Always use "external application"  instead of "third party" , see comments directly in the code
